name: personal-portfolio

on: [push]

jobs:
  master:
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - id: upload-files
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: ./
          destination: www.juangro.com
