name: personal-portfolio

on: [push]

jobs:
  master:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - id: upload-files
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.GCP_KEY }}
          path: ./assets
          destination: www.juangro.com
